#!/bin/bash

set -e

cd /var/lib/docker

if [ $# -eq 0 ]; then
	echo 2>&1 'Usage: docker-find CONTAINER'
	exit 1
fi

CID="$(docker inspect -f '{{.Id}}' "$1")"
shift

FIND_PATHS=()
FIND_OPTIONS=()
while [ $# -gt 0 ]; do
	case "$1" in
		-*)
			FIND_OPTIONS=("$@")
			break
			;;
		*)
			FIND_PATHS+=("$1")
			;;
	esac

	shift
done

for layer in $(cat aufs/layers/$CID); do
	find "${FIND_PATHS[*]/#/$(pwd)\/aufs\/diff\/$layer\/}" \
		"${FIND_OPTIONS[*]}" 2>/dev/null || true
done
