#!/bin/bash

set -e

cd /var/lib/docker

if [ $# -eq 0 ]; then
	echo 2>&1 'Usage: docker-find CONTAINER'
	exit 1
fi

CID="$(docker inspect -f '{{.Id}}' "$1")"
shift

FIND_PATHS=()
FIND_OPTIONS=()
while [ $# -gt 0 ]; do
	case "$1" in
		-*|!)
			FIND_OPTIONS=("$@")
			break
			;;
		/*)
			FIND_PATHS+=("$1")
			;;
		*)
			FIND_PATHS+=("/$1")
			;;
	esac

	shift
done

if [ ${#FIND_PATHS[*]} -eq 0 ]; then
	FIND_PATHS=("/")
fi

for layer in $(cat aufs/layers/$CID); do
	shortid="$(echo "$layer" | cut -c-12)"
	find ${FIND_PATHS[*]/#/$(pwd)\/aufs\/diff\/$layer} \
		${FIND_OPTIONS[*]} 2>/dev/null \
		| sed -r "s!^$(pwd)/aufs/diff/$layer!$shortid:!" \
		|| true
done
