#!/bin/bash

set -e

cd /var/lib/docker

if [[ $# -eq 0 ]]; then
	echo 2>&1 'Usage: docker-find CONTAINER_OR_IMAGE [FIND ARGUMENTS]'
	exit 1
fi

ID="$(docker inspect -f '{{.Id}}' "$1")"
shift

FIND_PATHS=()
FIND_OPTIONS=()
while [[ $# -gt 0 ]]; do
	case "$1" in
		-*|!)
			FIND_OPTIONS=("$@")
			break
			;;
		/*)
			FIND_PATHS+=("$1")
			;;
		*)
			FIND_PATHS+=("/$1")
			;;
	esac

	shift
done

if [[ ${#FIND_PATHS[*]} -eq 0 ]]; then
	FIND_PATHS=("/")
fi

if [[ ! -d aufs/layers ]]; then
	echo 2>&1 'docker-find only supports AUFS'
	exit 1
fi

for layer in $ID $(cat aufs/layers/$ID); do
	shortid="${layer:0:12}"
	if [[ "$layer" = *-init ]]; then
		shortid="${shortid}-init"
	fi
	find ${FIND_PATHS[*]/#/$(pwd)\/aufs\/diff\/$layer} \
		${FIND_OPTIONS[*]} 2>/dev/null \
		| sed -r "s!$(pwd)/aufs/diff/$layer!$shortid:!" \
		|| true
done
